import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import {
  ArrowRight,
  BarChart3,
  CheckCircle2,
  DollarSign,
  Share2,
  Zap,
  FileText,
  Lock,
  TrendingDown,
} from "lucide-react";

const SOCIAL_PROOF_STATS = [
  { value: "$12,400", label: "avg. yearly savings identified" },
  { value: "2 min", label: "to complete an audit" },
  { value: "100%", label: "free, no account required" },
];

const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Enter your AI tools",
    description:
      "Add each AI subscription — tool name, plan, monthly cost, seats, and what you use it for.",
  },
  {
    step: "02",
    title: "Engine audits your stack",
    description:
      "Our rules engine checks for plan overkill, tool overlap, API switching opportunities, and negotiation levers.",
  },
  {
    step: "03",
    title: "Get your savings report",
    description:
      "Receive a prioritized list of recommendations with exact dollar figures and action steps.",
  },
  {
    step: "04",
    title: "Share or save your report",
    description:
      "Email the report to yourself or share a permanent public URL with your team or investors.",
  },
];

const FEATURES = [
  {
    icon: TrendingDown,
    title: "Downgrade detection",
    description:
      "Identifies when a team plan is overkill for your actual seat count and recommends cheaper alternatives.",
  },
  {
    icon: BarChart3,
    title: "Overlap analysis",
    description:
      "Catches redundant tools serving the same use case so you can consolidate intelligently.",
  },
  {
    icon: DollarSign,
    title: "API cost modeling",
    description:
      "For high-volume users, calculates when switching to direct API access beats seat-based pricing.",
  },
  {
    icon: FileText,
    title: "AI-written summary",
    description:
      "A personalized audit narrative generated by AI, explaining your specific situation in plain English.",
  },
  {
    icon: Share2,
    title: "Shareable audit URL",
    description:
      "Every audit gets a permanent public link — share with your CFO, investors, or co-founders.",
  },
  {
    icon: Lock,
    title: "No account required",
    description:
      "Run a full audit in under 2 minutes. Your data is yours — we only store anonymized audit results.",
  },
];

const EXAMPLE_SAVINGS = [
  {
    tool: "ChatGPT Team",
    issue: "Team plan, only 2 users",
    saving: "$70/mo",
    type: "Downgrade",
  },
  {
    tool: "Jasper + ChatGPT",
    issue: "Overlapping writing use cases",
    saving: "$49/mo",
    type: "Consolidate",
  },
  {
    tool: "GitHub Copilot Enterprise",
    issue: "Individual plan covers your use case",
    saving: "$20/seat/mo",
    type: "Downgrade",
  },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col bg-white dark:bg-zinc-950">
      <Header />

      <main className="flex-1">
        {/* ─── Hero ──────────────────────────────────────────────────────── */}
        <section className="relative overflow-hidden border-b border-zinc-100 dark:border-zinc-900">
          <div className="mx-auto max-w-6xl px-4 py-24 sm:px-6 sm:py-32 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-400">
                <Zap className="h-3 w-3" aria-hidden="true" />
                Free AI spend audit — results in 2 minutes
              </div>

              <h1 className="text-4xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-5xl lg:text-6xl">
                Your team is probably
                <br />
                <span className="text-emerald-600">overpaying for AI.</span>
              </h1>

              <p className="mx-auto mt-6 max-w-2xl text-lg text-zinc-500 dark:text-zinc-400">
                StackSave audits your AI tooling subscriptions and identifies
                exactly where you&apos;re leaving money on the table — with
                specific, actionable recommendations and dollar figures.
              </p>

              <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
                <Button asChild variant="accent" size="lg" className="gap-2">
                  <Link href="/audit">
                    Run your free audit
                    <ArrowRight className="h-4 w-4" aria-hidden="true" />
                  </Link>
                </Button>
                <Button asChild variant="outline" size="lg">
                  <Link href="/#how-it-works">See how it works</Link>
                </Button>
              </div>

              {/* Social proof strip */}
              <div className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-3">
                {SOCIAL_PROOF_STATS.map((stat) => (
                  <div key={stat.label} className="text-center">
                    <div className="text-2xl font-bold text-zinc-900 dark:text-white">
                      {stat.value}
                    </div>
                    <div className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
                      {stat.label}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ─── Example Savings ───────────────────────────────────────────── */}
        <section className="border-b border-zinc-100 bg-zinc-50 dark:border-zinc-900 dark:bg-zinc-900/50">
          <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8">
            <p className="mb-8 text-center text-sm font-medium uppercase tracking-widest text-zinc-400 dark:text-zinc-500">
              Common findings from audits
            </p>
            <div className="grid gap-4 sm:grid-cols-3">
              {EXAMPLE_SAVINGS.map((example) => (
                <div
                  key={example.tool}
                  className="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"
                >
                  <div className="mb-3 flex items-center justify-between">
                    <span className="text-xs font-semibold uppercase tracking-wide text-emerald-600 dark:text-emerald-400">
                      {example.type}
                    </span>
                    <span className="text-sm font-bold text-zinc-900 dark:text-white">
                      Save {example.saving}
                    </span>
                  </div>
                  <p className="text-sm font-medium text-zinc-900 dark:text-white">
                    {example.tool}
                  </p>
                  <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                    {example.issue}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── How It Works ──────────────────────────────────────────────── */}
        <section id="how-it-works" className="border-b border-zinc-100 dark:border-zinc-900">
          <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-4xl">
                How StackSave works
              </h2>
              <p className="mt-4 text-zinc-500 dark:text-zinc-400">
                No AI black boxes. Transparent rules-based analysis you can
                actually trust.
              </p>
            </div>

            <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
              {HOW_IT_WORKS_STEPS.map((step) => (
                <div key={step.step} className="relative">
                  <div className="mb-4 text-4xl font-bold text-zinc-100 dark:text-zinc-800">
                    {step.step}
                  </div>
                  <h3 className="mb-2 font-semibold text-zinc-900 dark:text-white">
                    {step.title}
                  </h3>
                  <p className="text-sm text-zinc-500 dark:text-zinc-400">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── Features ──────────────────────────────────────────────────── */}
        <section
          id="features"
          className="border-b border-zinc-100 bg-zinc-50 dark:border-zinc-900 dark:bg-zinc-900/50"
        >
          <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-4xl">
                Everything you need to cut AI waste
              </h2>
            </div>

            <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {FEATURES.map((feature) => (
                <div
                  key={feature.title}
                  className="flex gap-4"
                >
                  <div className="mt-1 flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">
                    <feature.icon
                      className="h-4 w-4 text-zinc-600 dark:text-zinc-400"
                      aria-hidden="true"
                    />
                  </div>
                  <div>
                    <h3 className="font-semibold text-zinc-900 dark:text-white">
                      {feature.title}
                    </h3>
                    <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
                      {feature.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── CTA ───────────────────────────────────────────────────────── */}
        <section className="bg-zinc-900 dark:bg-zinc-950">
          <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
                Find your savings in 2 minutes.
              </h2>
              <p className="mt-4 text-zinc-400">
                Free, no account, no credit card. Just answers.
              </p>

              <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
                <Button asChild variant="accent" size="lg" className="gap-2">
                  <Link href="/audit">
                    Start free audit
                    <ArrowRight className="h-4 w-4" aria-hidden="true" />
                  </Link>
                </Button>
              </div>

              <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row sm:gap-6">
                {["No account needed", "Results in 2 minutes", "Shareable report"].map(
                  (point) => (
                    <div
                      key={point}
                      className="flex items-center gap-2 text-sm text-zinc-400"
                    >
                      <CheckCircle2
                        className="h-4 w-4 text-emerald-500"
                        aria-hidden="true"
                      />
                      {point}
                    </div>
                  )
                )}
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
